github: add setup-terraform action
The `terraform_wrapper` has to be disabled because otherwise it seems to mangle
.go files causing those failures in `make test`:

> go get -d -t ./...
> go test -parallel $(nproc) -race -timeout 60m -v ./lxd
> === RUN   TestAccContainer_importBasic
>     import_resource_lxd_container_test.go:14: Step 1/2 error: Error retrieving pre-apply state: invalid character 'c' looking for beginning of value
>     testing_new.go:77: Error retrieving state, there may be dangling resources: invalid character 'c' looking for beginning of value
> --- FAIL: TestAccContainer_importBasic (1.96s)

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>